name: Sync to Vercel Repo

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Full history for proper mirroring

      - name: Setup SSH key
        env:
          DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo "$DEPLOY_KEY" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan github.com >> ~/.ssh/known_hosts

      - name: Mirror to target repo
        run: |
          git config --global user.name "GitHub Sync Bot"
          git config --global user.email "syncbot@example.com"
          git remote add target git@github.com:chikaAcaFaca/bzr-portal1.git
          git push --force target main

      - name: Notify sync success
        if: success()
        run: echo "✅ Successfully synced to chikaAcaFaca/bzr-portal1"

      - name: Notify sync failure
        if: failure()
        run: echo "❌ Failed to sync to chikaAcaFaca/bzr-portal1"
